version: 2.1
orbs:
  aws-cli: circleci/aws-cli@5.2.0
  terraform: circleci/terraform@3.6.0
jobs:
  aws-example:
    environment:
      AWS_REGION: us-east-1
#      TF_CLOUD_API_TOKEN: ${TFE_TOKEN}
    executor: terraform/default
#    docker:
#      - image: cimg/aws:2023.06
    steps:
      - checkout
      - aws-cli/setup:
          role_arn: ${AWS_ROLE_ARN}
          region: ${AWS_REGION}
#      - terraform/install:
      - terraform/fmt:
          path: ./terraform
      - terraform/validate:
          path: ./terraform
      - terraform/init:
          backend: true
          path: ./terraform
          environment:
            TF_CLOUD_API_TOKEN: ${TFE_TOKEN}
      - terraform/plan:
          path: ./terraform
      - terraform/apply:
          path: ./terraform
workflows:
  aws-example:
    jobs:
      - aws-example:
          context: terraform
      
